In [1]:
!wget https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-02.parquet

--2023-10-16 14:01:13--  https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-02.parquet
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 18.67.246.167, 18.67.246.186, 18.67.246.47, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|18.67.246.167|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 45616512 (44M) [application/x-www-form-urlencoded]
Saving to: ‘yellow_tripdata_2022-02.parquet’

yellow_tripdata_202 100%[===================>]  43.50M  7.24MB/s    in 6.4s

2023-10-16 14:01:20 (6.78 MB/s) - ‘yellow_tripdata_2022-02.parquet’ saved [45616512/45616512]

In [11]:
!ls -l

total 282392
-rw-r--r-- 1 root root     7530 Oct 16 14:05 Untitled.ipynb
-rw-r--r-- 1 root root 45616512 Jun 30  2022 yellow_tripdata_2022-02.parquet
-rw-r--r-- 1 root root 45949452 Oct 16 14:07 yellow_tripdata_gzip.parquet
-rw-r--r-- 1 root root 59836169 Oct 16 14:06 yellow_tripdata_lz4.parquet
-rw-r--r-- 1 root root 60099872 Oct 16 14:06 yellow_tripdata_snappy.parquet
-rw-r--r-- 1 root root 77651932 Oct 16 14:06 yellow_tripdata_uncompressed.parquet

In [14]:
!pip3 install pyarrow pandas

Requirement already satisfied: pyarrow in /usr/local/lib/python3.8/dist-packages (13.0.0)
Collecting pandas
  Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 5.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.8/dist-packages (from pyarrow) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Collecting tzdata>=2022.1
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 5.1 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: tzdata, pandas
Successfully installed pandas-2.0.3 tzdata-2023.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py", line 1752, in print
    extend(render(renderable, render_options))
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py", line 1390, in render
    for render_output in iter_render:
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/segment.py", line 245, in split_lines
    for segment in segments:
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py", line 1368, in render
    renderable = rich_cast(renderable)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
    if found_executable and os.path.samefile(
  File "/usr/lib/python3.8/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'
Call stack:
  File "/usr/local/bin/pip3", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/req_command.py", line 148, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py", line 237, in pip_self_version_check
    logger.info("[present-rich] %s", upgrade_prompt)
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.1.2', new='23.3'),)

In [6]:
import pyarrow.parquet as pq

In [7]:
trips = pq.read_table("yellow_tripdata_2022-02.parquet", use_legacy_dataset=True)

/tmp/ipykernel_1129/3462804385.py:1: FutureWarning: Passing 'use_legacy_dataset=True' to get the legacy behaviour is deprecated as of pyarrow 8.0.0, and the legacy implementation will be removed in a future version.
  trips=pq.read_table("yellow_tripdata_2022-02.parquet", use_legacy_dataset=True)

In [9]:
pq.write_table(trips, "yellow_tripdata_uncompressed.parquet", compression="none")
pq.write_table(trips, "yellow_tripdata_snappy.parquet", compression="snappy")
pq.write_table(trips, "yellow_tripdata_lz4.parquet", compression="lz4")
pq.write_table(trips, "yellow_tripdata_gzip.parquet", compression="gzip")

In [10]:
!ls -l

total 282392
-rw-r--r-- 1 root root     7530 Oct 16 14:05 Untitled.ipynb
-rw-r--r-- 1 root root 45616512 Jun 30  2022 yellow_tripdata_2022-02.parquet
-rw-r--r-- 1 root root 45949452 Oct 16 14:07 yellow_tripdata_gzip.parquet
-rw-r--r-- 1 root root 59836169 Oct 16 14:06 yellow_tripdata_lz4.parquet
-rw-r--r-- 1 root root 60099872 Oct 16 14:06 yellow_tripdata_snappy.parquet
-rw-r--r-- 1 root root 77651932 Oct 16 14:06 yellow_tripdata_uncompressed.parquet

In [15]:
pt = trips.to_pandas()
pt

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2022-02-01 00:06:58,2022-02-01 00:19:24,1.0,5.40,1.0,N,138,252,1,17.00,1.75,0.5,3.90,0.00,0.3,23.45,0.0,1.25
1,1,2022-02-01 00:38:22,2022-02-01 00:55:55,1.0,6.40,1.0,N,138,41,2,21.00,1.75,0.5,0.00,6.55,0.3,30.10,0.0,1.25
2,1,2022-02-01 00:03:20,2022-02-01 00:26:59,1.0,12.50,1.0,N,138,200,2,35.50,1.75,0.5,0.00,6.55,0.3,44.60,0.0,1.25
3,2,2022-02-01 00:08:00,2022-02-01 00:28:05,1.0,9.88,1.0,N,239,200,2,28.00,0.50,0.5,0.00,3.00,0.3,34.80,2.5,0.00
4,2,2022-02-01 00:06:48,2022-02-01 00:33:07,1.0,12.16,1.0,N,138,125,1,35.50,0.50,0.5,8.11,0.00,0.3,48.66,2.5,1.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2979426,2,2022-02-28 23:50:00,2022-03-01 00:06:00,NaN,3.40,NaN,None,163,193,0,14.37,0.00,0.5,0.00,0.00,0.3,17.67,NaN,NaN
2979427,2,2022-02-28 23:06:57,2022-02-28 23:19:12,NaN,3.48,NaN,None,141,4,0,14.51,0.00,0.5,2.00,0.00,0.3,19.81,NaN,NaN
2979428,2,2022-02-28 23:48:13,2022-03-01 00:03:33,NaN,3.05,NaN,None,161,151,0,14.38,0.00,0.5,3.81,0.00,0.3,21.49,NaN,NaN
2979429,2,2022-02-28 23:56:41,2022-03-01 00:04:57,NaN,2.62,NaN,None,141,226,0,12.53,0.00,0.5,1.71,0.00,0.3,17.54,NaN,NaN
2979430,2,2022-02-28 23:04:00,2022-02-28 23:10:00,NaN,1.41,NaN,None,237,142,0,8.80,0.00,0.5,2.57,0.00,0.3,14.67,NaN,NaN

In [16]:
trips = pq.read_table("yellow_tripdata_lz4.parquet")
trips

pyarrow.Table
VendorID: int64
tpep_pickup_datetime: timestamp[us]
tpep_dropoff_datetime: timestamp[us]
passenger_count: double
trip_distance: double
RatecodeID: double
store_and_fwd_flag: string
PULocationID: int64
DOLocationID: int64
payment_type: int64
fare_amount: double
extra: double
mta_tax: double
tip_amount: double
tolls_amount: double
improvement_surcharge: double
total_amount: double
congestion_surcharge: double
airport_fee: double
----
VendorID: [[1,1,1,2,2,...,2,2,2,2,2],[2,1,1,2,2,...,2,2,1,1,2],...,[2,2,2,2,2,...,1,2,2,1,2],[2,2,2,2,6,...,2,2,2,2,2]]
tpep_pickup_datetime: [[2022-02-01 00:06:58.000000,2022-02-01 00:38:22.000000,2022-02-01 00:03:20.000000,2022-02-01 00:08:00.000000,2022-02-01 00:06:48.000000,...,2022-02-02 15:12:42.000000,2022-02-02 15:25:12.000000,2022-02-02 15:47:16.000000,2022-02-02 15:43:17.000000,2022-02-02 15:10:01.000000],[2022-02-02 15:20:28.000000,2022-02-02 15:13:14.000000,2022-02-02 15:28:55.000000,2022-02-02 15:37:14.000000,2022-02-02 15:42:23.000000,...,2022-02-03 20:14:29.000000,2022-02-03 20:43:39.000000,2022-02-03 20:14:07.000000,2022-02-03 20:48:24.000000,2022-02-03 20:55:31.000000],...,[2022-02-27 17:30:59.000000,2022-02-27 17:54:06.000000,2022-02-27 17:08:57.000000,2022-02-27 17:01:12.000000,2022-02-27 17:21:03.000000,...,2022-02-02 19:52:23.000000,2022-02-02 19:52:04.000000,2022-02-02 19:25:00.000000,2022-02-02 19:39:06.000000,2022-02-02 19:10:26.000000],[2022-02-02 19:14:52.000000,2022-02-02 19:08:26.000000,2022-02-02 19:22:41.000000,2022-02-02 19:19:00.000000,2022-02-02 19:02:41.000000,...,2022-02-28 23:50:00.000000,2022-02-28 23:06:57.000000,2022-02-28 23:48:13.000000,2022-02-28 23:56:41.000000,2022-02-28 23:04:00.000000]]
tpep_dropoff_datetime: [[2022-02-01 00:19:24.000000,2022-02-01 00:55:55.000000,2022-02-01 00:26:59.000000,2022-02-01 00:28:05.000000,2022-02-01 00:33:07.000000,...,2022-02-02 15:14:15.000000,2022-02-02 15:36:33.000000,2022-02-02 16:00:49.000000,2022-02-02 15:47:36.000000,2022-02-02 15:19:21.000000],[2022-02-02 15:32:13.000000,2022-02-02 15:16:41.000000,2022-02-02 15:38:11.000000,2022-02-02 15:48:26.000000,2022-02-02 16:03:26.000000,...,2022-02-03 20:32:21.000000,2022-02-03 21:00:01.000000,2022-02-03 20:19:46.000000,2022-02-03 21:09:43.000000,2022-02-03 21:13:45.000000],...,[2022-02-27 17:51:50.000000,2022-02-27 17:58:03.000000,2022-02-27 17:16:06.000000,2022-02-27 17:12:43.000000,2022-02-27 17:36:02.000000,...,2022-02-02 20:32:44.000000,2022-02-02 20:07:08.000000,2022-02-02 19:41:00.000000,2022-02-02 19:42:00.000000,2022-02-02 19:31:57.000000],[2022-02-02 19:40:56.000000,2022-02-02 19:24:59.000000,2022-02-02 19:41:24.000000,2022-02-02 19:40:00.000000,2022-02-02 20:02:20.000000,...,2022-03-01 00:06:00.000000,2022-02-28 23:19:12.000000,2022-03-01 00:03:33.000000,2022-03-01 00:04:57.000000,2022-02-28 23:10:00.000000]]
passenger_count: [[1,1,1,1,1,...,1,1,1,1,1],[1,1,1,1,1,...,2,2,0,0,1],...,[1,1,3,2,1,...,null,null,null,null,null],[null,null,null,null,null,...,null,null,null,null,null]]
trip_distance: [[5.4,6.4,12.5,9.88,12.16,...,0.28,1.2,3.29,0.46,1.32],[1.84,0.5,1.3,1.14,2.22,...,2.79,3.4,0.8,3,3.4],...,[3.79,0.61,1.2,1.64,2.5,...,9.6,2.57,2.73,0.5,5.09],[7.79,7.58,3.93,3.17,8.67,...,3.4,3.48,3.05,2.62,1.41]]
RatecodeID: [[1,1,1,1,1,...,1,1,1,1,1],[1,1,1,1,1,...,1,1,1,1,1],...,[1,1,1,1,1,...,null,null,null,null,null],[null,null,null,null,null,...,null,null,null,null,null]]
store_and_fwd_flag: [["N","N","N","N","N",...,"N","N","N","N","N"],["N","N","N","N","N",...,"N","N","N","N","N"],...,["N","N","N","N","N",...,null,null,null,null,null],[null,null,null,null,null,...,null,null,null,null,null]]
PULocationID: [[138,138,138,239,138,...,238,239,238,90,164],[161,170,264,239,170,...,237,100,114,234,161],...,[237,68,79,68,125,...,163,45,170,263,24],[88,244,162,169,265,...,163,141,161,141,237]]
DOLocationID: [[252,41,200,200,125,...,238,151,142,90,161],[68,170,229,238,236,...,48,151,90,186,211],...,[68,249,148,249,68,...,61,164,114,263,243],[236,48,148,247,39,...,193,4,151,226,142]]
payment_type: [[1,2,2,2,1,...,2,1,1,1,1],[1,1,1,2,1,...,1,1,1,1,1],...,[1,1,1,1,1,...,0,0,0,0,0],[0,0,0,0,0,...,0,0,0,0,0]]
...